---
name: 🔀 CS - Rebase
description: This action rebase the specific branch into the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The branch to rebase from
    required: true
  TO:
    description: The branch to rebase into
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Git
      shell: bash
      permissions:
        contents: write
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes then rebase
      shell: bash
      run: |
        git fetch origin ${{ inputs.FROM }} || { echo "❌ Branch ${{ inputs.FROM }} not found"; exit 1; }
        git fetch origin ${{ inputs.TO }}
        git checkout ${{ inputs.TO }}
        git reset --hard origin/${{ inputs.TO }}
        git rebase --onto origin/${{ inputs.FROM }} origin/${{ inputs.TO }} ${{ inputs.TO }}
        git push origin ${{ inputs.TO }} --force-with-lease
