---
name: 🔀 CS - Rebase
description: This action rebase the specific branch into the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The branch to rebase from
    required: true
  TO:
    description: The branch to rebase into
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Git & Auth
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.GH_TOKEN }}@github.com/${{ github.repository }}

    - name: Rebase and Push
      shell: bash
      run: |
        git fetch origin ${{ inputs.FROM }}
        git fetch origin ${{ inputs.TO }}

        git checkout ${{ inputs.TO }}
        git reset --hard origin/${{ inputs.TO }}

        git rebase origin/${{ inputs.FROM }}

        git push origin ${{ inputs.TO }} --force-with-lease
