name: 📝 CI - Commit Changes
description: This action commits changes to the repository
inputs:
  GH_TOKEN:
    description: "GitHub token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: 🚨 Check if there are changes to commit
      shell: bash
      run: |
        if git diff --exit-code; then
            echo "HAVE_CHANGES=false" >> $GITHUB_ENV
        else
            echo "HAVE_CHANGES=true" >> $GITHUB_ENV
        fi
    - name: ✍️ Commit and push changes
      shell: bash
      if: env.HAVE_CHANGES == 'true'
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add --all
        git commit -m "chore(CI): update libs"
        git pull --rebase
        git push origin HEAD:main
