---
name: 🛠️ Lint
description: This action lints the project
runs:
  using: "composite"
  steps:
    - name: Lint YAML
      uses: ./actions/lint-yaml

    - name: Run lint
      shell: bash
      run: pnpm run --if-present lint
