name: 🔥 CS - Trigger Events
description: This action triggers multiple events for a single repository
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  REPO:
    description: Repository to trigger events for
    required: true
  EVENTS:
    description: Comma-separated list of event types to trigger (supporting spaces and icons)
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger events in the repository
      shell: bash
      run: |
        IFS='\n' read -ra EVENTS <<< "${{ inputs.EVENTS }}"
        for event in "${EVENTS[@]}"; do
          event_trimmed=$(echo "$event" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          curl -X POST \
          -H "Authorization: token ${{ inputs.GH_TOKEN }}" \
          -d "{\"event_type\": \"$event_trimmed\"}" \
          https://api.github.com/repos/${{ inputs.REPO }}/dispatches
        done
