name: 🔀 CS - Merge
description: This action merge the specific branch into the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The branch to merge from
    required: true
  TO:
    description: The branch to merge into
    required: true
  CHOOSE_STRATEGY:
    description: The strategy to use for the merge
    required: false
    default: "theirs"
runs:
  using: "composite"
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "actions@github.com"
        git config user.email "${GITHUB_ACTOR}"

    - name: Pull latest changes then merge
      shell: bash
      run: |
        git checkout ${{ inputs.FROM }}
        git fetch origin
        git checkout ${{ inputs.TO }}
        git pull
        git merge origin/${{ inputs.FROM }} --allow-unrelated-histories --strategy-option ${{ inputs.CHOOSE_STRATEGY }}
        git push origin ${{ inputs.TO }}
