---
name: 🔀 CS - Merge
description: This action merge the specific branch into the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The branch to merge from
    required: true
  TO:
    description: The branch to merge into
    required: true
  CHOOSE_STRATEGY:
    description: The strategy to use for the merge
    required: false
    default: "theirs"
runs:
  using: "composite"
  steps:
    - name: Set up Git & Auth
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.GH_TOKEN }}@github.com/${{ github.repository }}

    - name: Merge and Push
      shell: bash
      run: |
        git fetch origin ${{ inputs.FROM }} || { echo "❌ Branch ${{ inputs.FROM }} not found"; exit 1; }
        git fetch origin ${{ inputs.TO }} || { echo "❌ Branch ${{ inputs.TO }} not found"; exit 1; }

        git checkout ${{ inputs.TO }}
        git reset --hard origin/${{ inputs.TO }}

        echo "Merging ${{ inputs.FROM }} into ${{ inputs.TO }} with strategy: ${{ inputs.CHOOSE_STRATEGY }}"
        git merge origin/${{ inputs.FROM }} --allow-unrelated-histories -X ${{ inputs.CHOOSE_STRATEGY }} -m "Merge ${{ inputs.FROM }} into ${{ inputs.TO }}"

        git push origin ${{ inputs.TO }}
