---
name: 🔧 CS - Env & Deps
description: This action sets up the environment and installs dependencies for the CI pipeline.
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061  # v4.2.0
      with:
        version: 10.25.0

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f  # v6.1.0
      with:
        node-version: "24.12.0"

    - name: Setup environment variables
      shell: bash
      run: |
        if [ -f ".env.example" ]; then
          cp .env.example .env
        else
          echo ".env.example not found. Skipping."
        fi

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
