name: 🔀 CS - Merge Branch
description: This action merge the specific branch into the target branch
inputs:
  GH_TOKEN:
    description: "GitHub token for authentication"
    required: true
  FROM:
    description: "The branch to merge from"
    required: true
  TO:
    description: "The branch to merge into"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "actions@github.com"
        git config user.email "${GITHUB_ACTOR}"

    - name: Pull latest changes then merge
      shell: bash
      run: |
        git checkout ${{ inputs.FROM }}
        git fetch origin
        git checkout ${{ inputs.TO }}
        git pull
        git merge origin/${{ inputs.FROM }} --ff-only --allow-unrelated-histories --strategy-option theirs 
        git push origin ${{ inputs.TO }}
