---
name: 🛠️ CS - Lint & Build
description: This action lints and builds the project
inputs:
  BUILD_ARTIFACT_NAME:
    description: Name of the build artifact
    required: false
runs:
  using: "composite"
  steps:
    - name: Lint YAML
      uses: cyberskill-world/.github/actions/lint-yaml@main

    - name: Run lint
      shell: bash
      run: pnpm run --if-present lint

    - name: Build project
      shell: bash
      run: pnpm run --if-present build

    - name: Upload build or dist folder as artifact
      if: ${{ inputs.BUILD_ARTIFACT_NAME != '' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: |
          dist
          build
