name: 🛠️ CI - Lint & Build
description: This action lints and builds the project

runs:
  using: "composite"
  steps:
    - name: 🧹 Run lint
      shell: bash
      run: cyberskill lint

    - name: 🏗️ Build project
      shell: bash
      run: cyberskill build
