name: 🛠️ CI - Lint & Build
description: This action lints and builds the project
runs:
  using: "composite"
  steps:
    - name: 🧹 Run lint
      shell: bash
      run: pnpm run --if-present lint
    - name: 🏗️ Build project
      shell: bash
      run: pnpm run --if-present build
    - name: 📤 Upload build or dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: BUILD_ARTIFACT
        path: |
          dist
          build
