---
name: 📜 CS - Create PR
description: This action creates a pull request from the source branch to the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The source branch
    required: true
  TO:
    description: The target branch
    required: true
  TITLE:
    description: Pull Request Title
    required: false
    default: "chore(CI): sync changes"
  BODY:
    description: Pull Request Body
    required: false
    default: "This PR syncs the latest changes."
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Create Pull Request
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        PR_BASE: ${{ inputs.TO }}
        PR_HEAD: ${{ inputs.FROM }}
        PR_TITLE: ${{ inputs.TITLE }}
        PR_BODY: ${{ inputs.BODY }}
      run: |
        gh pr create \
          --base "$PR_BASE" \
          --head "$PR_HEAD" \
          --title "$PR_TITLE" \
          --body "$PR_BODY"
