---
name: 📜 CS - Create PR
description: This action creates a pull request from the source branch to the target branch
inputs:
  GH_TOKEN:
    description: GitHub token for authentication
    required: true
  FROM:
    description: The source branch
    required: true
  TO:
    description: The target branch
    required: true
  TITLE:
    description: Pull Request Title
    required: false
    default: "chore(CI): sync changes"
  BODY:
    description: Pull Request Body
    required: false
    default: "This PR syncs the latest changes."
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Create Pull Request
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        gh pr create \
          --base ${{ inputs.TO }} \
          --head ${{ inputs.FROM }} \
          --title "${{ inputs.TITLE }}" \
          --body "${{ inputs.BODY }}"
