---
name: 🔍 Match Branch
description: This action checks if the current branch matches the target branch
inputs:
  BRANCH:
    description: Branch to check against
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if branch matches the target branch
      shell: bash
      env:
        TARGET_BRANCH: ${{ inputs.BRANCH }}
      run: |
        if [[ "$GITHUB_REF_NAME" != "$TARGET_BRANCH" ]]; then
          echo "Not on '$TARGET_BRANCH' branch (current: '$GITHUB_REF_NAME'). Skipping.";
          exit 0
        fi
        echo "On '$TARGET_BRANCH' branch. Continuing."
